### ISSUE TITLE
Readme unclear

### ISSUE THREAD

**Issue by duncdrum** [tunnckoCore/triage-new-issues#35]
Should the app run out of the box,  or does it require further configuration?

**Comment by olstenlarck** [comment]
It isn't on the npm i believe, but i'm not sure.

As about deployt, there is a section about it. Clone repo and follow it.

**Comment by olstenlarck** [comment]
Or if you want to use it, just go to https://github.com/apps/triage-new-issues and it will be added to your account or org.

**Comment by duncdrum** [comment]
I have added it to my personal account and to a separate org account, it appears as installed in the repo's settings. But new issues don't get labeled, do I maybe need to add a `conf.yml`?

**Comment by olstenlarck** [comment]
No. No need anything. Probably the Now.sh instance is freeze - it happens from time to time when no new issues are created. I'll restart it.

**Comment by olstenlarck** [comment]
Hm. Strange, probably. It seems it is `up`. It happens sometimes, don't know why. Not always creates labels, i noticed that too..

**Comment by olstenlarck** [comment]
@bkeepers, @gr2m, ideas?

**Comment by gr2m** [comment]
Have a look at https://github.com/settings/apps/triage-new-issues/advanced, it will show you the webhook event payloads, you will see the one that failed and why.

A now.sh instance gets put to sleep after 5 min without a request. The initial request to wake up the instance might take too long and time out. I usually setup monitoring with https://uptimerobot.com/ which pings the server once per minute and also lets me know if it’s down. That works great for me, hope it helps :)

**Comment by olstenlarck** [comment]
Oh cool. Forgot about the payload reports and Uptime Robot - used it before some years.

Anyway, the thing is that I don't know which one is failed. Assuming.. Didn't looked at the reports ;d

> A now.sh instance gets put to sleep after 5 min without a request. 

Hm. I knew that it is something like 1-4 hours? hm.

**Comment by duncdrum** [comment]
@olstenlarck happy to say that triage bot is alive and kicking, thanks for the quick help.

**Comment by olstenlarck** [comment]
@duncdrum :D Didn't touched it. That's very strange behaving - works from time to time ;D

**Comment by olstenlarck** [comment]
Activated Uptime Robot, monitoring, so hoping to be always up :)
